spring:
    datasource:
        url: jdbc:mysql://localhost:3306/eventos?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop